service: lambda-isemail-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

package:
  include:
    - node_modules/**
  exclude:
    - package.json

functions:
  isemail:
    handler: handler.isemail
    events:
      - http:
          path: isemail
          method: GET
          integration: lambda
          request:
            template:
              application/json: '{ "email" : "$input.params(''email'')" }'
