service: lambda-isemail-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  currentTime:
    handler: handler.isemail
    events:
      - http:
          path: check
          method: get
